use psy_doge_solana_core::programs::{GENERIC_BUFFER_BUILDER_PROGRAM_ID_STR, MANUAL_CLAIM_PROGRAM_ID_STR, PENDING_MINT_BUFFER_BUILDER_PROGRAM_ID_STR, TXO_BUFFER_BUILDER_PROGRAM_ID_STR};
use solana_program::pubkey::Pubkey;

pub const MANUAL_CLAIM_PROGRAM_ID: Pubkey = Pubkey::from_str_const(MANUAL_CLAIM_PROGRAM_ID_STR);
pub const TXO_BUFFER_BUILDER_PROGRAM_ID: Pubkey = Pubkey::from_str_const(TXO_BUFFER_BUILDER_PROGRAM_ID_STR);
pub const GENERIC_BUFFER_BUILDER_PROGRAM_ID: Pubkey = Pubkey::from_str_const(GENERIC_BUFFER_BUILDER_PROGRAM_ID_STR);
pub const PENDING_MINT_BUFFER_BUILDER_PROGRAM_ID: Pubkey = Pubkey::from_str_const(PENDING_MINT_BUFFER_BUILDER_PROGRAM_ID_STR);
