pub const TXO_BUFFER_BUILDER_PROGRAM_ID_STR: &str = "TXWhjswto9q6hfaGPuAhDS79wAHKfbMJLVR178xYAaQ";
pub const PENDING_MINT_BUFFER_BUILDER_PROGRAM_ID_STR: &str = "PMUSqycT1j5JTLmHk8frGSCido2h9VG1pyh2MPEa33o";
pub const GENERIC_BUFFER_BUILDER_PROGRAM_ID_STR: &str = "GBYLmevzPSBPWfWrJ1h9gNzHqUjDXETzHKL1AasLyKwC";
pub const MANUAL_CLAIM_PROGRAM_ID_STR: &str = "MCdYbqiK3uj36tohbMjsh3Ssg8iRSJmSHToNxW8TWWE";
pub const DOGE_BRIDGE_PROGRAM_ID_STR: &str = "DBjo5tqf2uwt4sg9JznSk9SBbEvsLixknN58y3trwCxJ";
pub const NOOP_SHIM_PROGRAM_ID_STR: &str = "FwDChsHWLwbhTiYQ4Sum5mjVWswECi9cmrA11GUFUuxi";
