use psy_bridge_core::{common_types::QHash256, crypto::hash::sha256::SHA256_ZERO_HASHES};

pub const PSY_DOGE_BRIDGE_BLOCK_HASH_CACHE_SIZE: usize = 32;
pub const PSY_DOGE_BRIDGE_BLOCK_TREE_HEIGHT: usize = 28;
pub const PSY_DOGE_BRIDGE_MAX_REORG_BLOCKS: usize = 10;

pub const AUTO_CLAIM_DEPOSITS_TREE_HEIGHT: usize = 32;
pub const AUTO_CLAIM_DEPOSITS_TREE_EMPTY_ROOT: QHash256 = SHA256_ZERO_HASHES[AUTO_CLAIM_DEPOSITS_TREE_HEIGHT];
pub const MANUAL_CLAIM_DEPOSITS_TREE_HEIGHT: usize = 32;
pub const MANUAL_CLAIM_DEPOSITS_TREE_EMPTY_ROOT: QHash256 = SHA256_ZERO_HASHES[MANUAL_CLAIM_DEPOSITS_TREE_HEIGHT];
pub const WITHDRAWALS_TREE_HEIGHT: usize = 32;
pub const WITHDRAWALS_TREE_EMPTY_ROOT: QHash256 = SHA256_ZERO_HASHES[WITHDRAWALS_TREE_HEIGHT];